name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: microsoft

    - name: Build with Maven
      run: mvn -B package --no-transfer-progress

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/my-image:${{ github.sha }}

    - name: Deploy to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Check if tests passed
      run: mvn -B test --no-transfer-progress
      continue-on-error: true

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '**/surefire-reports/TEST-*.xml'
        check_name: Unit Tests

    - name: Deploy to GitHub Container Registry
      if: ${{ job.status == 'success' }}
      run: docker push ghcr.io/${{ github.repository }}/my-image:${{ github.sha }}
